name: post-content-morning

on:
  schedule:
    - cron: '30 23 * * *' # runs every 5:03 WIB

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # execute run.py to post message
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          IFTTT_TWITTER_EVENT_NAME: ${{ secrets.IFTTT_TWITTER_EVENT_NAME }}
          IFTTT_TWITTER_API_KEY: ${{ secrets.IFTTT_TWITTER_API_KEY }}
        run: python run.py

